# Generated by Django 6.0.4 on 2026-07-04 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_listing_conversation',
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_rental_conversation',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_listing_8d1c0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_rental__2c103b_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['content_type', 'object_id'], name='chat_conver_content_0e6cb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('buyer', 'seller', 'content_type', 'object_id'), name='unique_conversation_per_object'),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='rental',
        ),
    ]
