[phases.setup]
nixPkgs = ["libmagic"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn lendogo.wsgi:application"
