# Generated by Django 6.0.4 on 2026-06-30 09:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('scam_keywords', models.TextField(blank=True, default='', help_text='Comma-separated keywords: iphone,macbook,ps5. Used for extra scrutiny')),
                ('min_sample_size', models.PositiveIntegerField(default=3, help_text='Min SOLD listings needed before scam detection activates for this category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Optional. Used for email password reset if provided', max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='REQUIRED. E.164 format: +265991234567. Used for SMS reset + WhatsApp + Airtel Money', max_length=128, region=None, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(db_index=True, default='Unnamed Item', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='10000yr: Decimal not Float. Money must be exact', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', help_text='e.g. Area 49, Lilongwe or Near Gateway Mall', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', help_text='ACTIVE/SOLD/INACTIVE. Replaces is_sold boolean', max_length=10)),
                ('is_sold', models.BooleanField(db_index=True, default=False)),
                ('is_boosted', models.BooleanField(db_index=True, default=False, help_text='True = shows first on homepage. Costs MK 500 for 7 days')),
                ('boost_expiry', models.DateTimeField(blank=True, db_index=True, help_text='Auto-set to +7 days on boost. Auto-expires in save()', null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0, help_text='Counts clicks on WhatsApp button. Proof of buyer interest')),
                ('video', models.FileField(blank=True, help_text='MP4, MOV. Max 50MB. Main product video', null=True, upload_to='listing_videos/')),
                ('suspicion_level', models.IntegerField(db_index=True, default=0, help_text='0=safe, 1=low, 2=medium popup, 3=high popup. Auto-calculated')),
                ('scam_warning', models.TextField(blank=True, help_text='Auto-generated warning from utils.py based on name + price comparison', null=True)),
                ('market_avg_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cached average from other Lendogo listings. Used for popup display', max_digits=12, null=True)),
                ('last_scanned', models.DateTimeField(blank=True, db_index=True, help_text='Last time AI scanned this listing. Used to avoid re-scanning', null=True)),
                ('scam_score', models.IntegerField(db_index=True, default=0, help_text='0-100. Legacy field. Use suspicion_level instead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bumped_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Select category. System auto-compares to Malawi market average', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='lendogo.category')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_boosted', '-bumped_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_convos', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_convos', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='lendogo.listing')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lendogo.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='MP4, max 50MB', upload_to='listings/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lendogo.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='lendogo.listing')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lendogo.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='Unnamed Item', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rental_type', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month')], default='day', max_length=10)),
                ('location', models.CharField(blank=True, default='Lilongwe', max_length=100)),
                ('contact', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(choices=[('cars', 'Cars & Vehicles'), ('ps_system', 'PS / Gaming Systems'), ('tents', 'Tents'), ('chairs', 'Chairs'), ('halls', 'Halls for Weddings'), ('garden', 'Garden Equipment'), ('tools', 'Tools & Equipment'), ('electronics', 'Electronics'), ('sound', 'Sound Systems'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rental_images/')),
                ('images', models.JSONField(blank=True, default=list)),
                ('video', models.FileField(blank=True, help_text='MP4, MOV. Max 50MB', null=True, upload_to='rental_videos/')),
                ('deposit_required', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_from', models.DateField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='lendogo.rentallisting'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Manual verification by Lendogo team. Shows badge on dashboard + listings')),
                ('total_sales', models.PositiveIntegerField(default=0, help_text='Cached count. Updated when Listing.status changes to SOLD')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='lendogo.listing')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-created_at'], name='lendogo_lis_status_6dc2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location', 'status'], name='lendogo_lis_locatio_b1b62a_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_boosted', 'status', '-created_at'], name='lendogo_lis_is_boos_7e8fad_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'status'], name='lendogo_lis_seller__119645_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['whatsapp_clicks'], name='lendogo_lis_whatsap_8ec806_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['suspicion_level'], name='lendogo_lis_suspici_0bfac9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'status'], name='lendogo_lis_categor_5016d3_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['product', 'status', 'suspicion_level'], name='lendogo_lis_product_bc4ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='lendogo_lis_price_dd267b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['last_scanned'], name='lendogo_lis_last_sc_85e38d_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['listing', '-viewed_at'], name='lendogo_lis_listing_1d3e71_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['ip_address', 'listing', '-viewed_at'], name='lendogo_lis_ip_addr_e3cc56_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read', 'created_at'], name='lendogo_mes_convers_2c77aa_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='lendogo_mes_sender__de2755_idx'),
        ),
        migrations.AddIndex(
            model_name='rentallisting',
            index=models.Index(fields=['location', 'is_active', '-created_at'], name='lendogo_ren_locatio_3285bc_idx'),
        ),
        migrations.AddIndex(
            model_name='rentallisting',
            index=models.Index(fields=['category', 'is_active', '-created_at'], name='lendogo_ren_categor_dd6f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='rentallisting',
            index=models.Index(fields=['is_active', '-views'], name='lendogo_ren_is_acti_7d9cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='rentallisting',
            index=models.Index(fields=['seller', '-created_at'], name='lendogo_ren_seller__1e3536_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['buyer', '-updated_at'], name='lendogo_con_buyer_i_fc8743_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['seller', '-updated_at'], name='lendogo_con_seller__f247f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('listing', 'buyer', 'seller'), ('rental', 'buyer', 'seller')},
        ),
        migrations.AddIndex(
            model_name='whatsappclick',
            index=models.Index(fields=['listing', '-clicked_at'], name='lendogo_wha_listing_859123_idx'),
        ),
    ]
