# Generated by Django 6.0.4 on 2026-07-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_lendogo_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='AUTO: True if seller verified + low suspicion + good history. Premium badge'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_verified',
            field=models.BooleanField(db_index=True, default=False, help_text="AUTO: True if has real images + price matches category. Shows 'Photo Verified' badge"),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['photo_verified'], name='lendogo_lis_photo_v_e1a031_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_lendogo_verified'], name='lendogo_lis_is_lend_f03b61_idx'),
        ),
    ]
