# Generated by Django 6.0.4 on 2026-07-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendogo', '0002_listing_is_lendogo_verified_listing_photo_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='boost_tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
