# Generated by Django 6.0.4 on 2026-07-20 09:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendogo', '0003_listing_boost_tx_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rentallisting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='whatsappclick',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='lendogo_con_buyer_i_fc8743_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='lendogo_con_seller__f247f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='lendogo_lis_photo_v_e1a031_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='lendogo_lis_is_lend_f03b61_idx',
        ),
        migrations.RemoveIndex(
            model_name='listingview',
            name='lendogo_lis_listing_1d3e71_idx',
        ),
        migrations.RemoveIndex(
            model_name='listingview',
            name='lendogo_lis_ip_addr_e3cc56_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='lendogo_mes_convers_2c77aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='lendogo_mes_sender__de2755_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentallisting',
            name='lendogo_ren_locatio_3285bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentallisting',
            name='lendogo_ren_categor_dd6f4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentallisting',
            name='lendogo_ren_is_acti_7d9cdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentallisting',
            name='lendogo_ren_seller__1e3536_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappclick',
            name='lendogo_wha_listing_859123_idx',
        ),
        migrations.AddField(
            model_name='listing',
            name='boost_started_at',
            field=models.DateTimeField(blank=True, help_text='Auto set when you tick boost', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_sample_size',
            field=models.PositiveIntegerField(default=2, help_text='Min ACTIVE listings needed before scam detection activates'),
        ),
        migrations.AlterField(
            model_name='category',
            name='scam_keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='boost_tx_ref',
            field=models.CharField(blank=True, help_text='Keep for paychangu later', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='lendogo.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_boosted',
            field=models.BooleanField(db_index=True, default=False, help_text='Tick to boost for 7 days. Shows at top of home'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_lendogo_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_scanned',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='market_avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='scam_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='scam_warning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='suspicion_level',
            field=models.IntegerField(db_index=True, default=0, help_text='0=safe, 1=low, 2=medium, 3=high. Auto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listing_videos/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentallisting',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rental_videos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='boost_expiry',
        ),
    ]
