# Generated by Django 6.0.4 on 2026-07-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendogo', '0004_alter_listingview_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified_manual',
            field=models.BooleanField(db_index=True, default=False, help_text='Manual tick by admin for friends'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
