# Generated by Django 6.0.4 on 2026-06-30 09:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome class e.g. fa-bolt', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order on site')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(db_index=True, help_text='Format: +265XXXXXXXXX', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be in format +265XXXXXXXXX', regex='^\\+265\\d{9}$')])),
                ('location', models.CharField(db_index=True, help_text='Area 25, Area 18, City Centre', max_length=100)),
                ('rate', models.PositiveIntegerField(help_text='Call-out fee in MWK. Min 1000', validators=[django.core.validators.MinValueValidator(1000)])),
                ('bio', models.TextField(blank=True, help_text='Describe your experience')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(db_index=True, default=5.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('reviews_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='You manually verify ID')),
                ('has_airtel_money', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='workers/photos/%Y/%m/')),
                ('id_photo', models.ImageField(help_text='National ID for verification', upload_to='workers/ids/%Y/%m/')),
                ('work_photo', models.ImageField(blank=True, null=True, upload_to='workers/work/%Y/%m/')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Show on public site after verification')),
                ('responds_fast', models.BooleanField(default=False, help_text='Badge: Responds in 1hr')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='services.skill')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'ordering': ['-is_verified', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone must be in format +265XXXXXXXXX', regex='^\\+265\\d{9}$')])),
                ('rating', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.worker')),
            ],
            options={
                'verbose_name': 'Worker Review',
                'verbose_name_plural': 'Worker Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['is_active', 'is_verified', 'skill'], name='services_wo_is_acti_cc7b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['location'], name='services_wo_locatio_2d96fe_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['-created_at'], name='services_wo_created_a834ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1.0), ('rating__lte', 5.0)), name='rating_range_check'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 1000)), name='min_rate_check'),
        ),
        migrations.AddIndex(
            model_name='workerreview',
            index=models.Index(fields=['worker', 'is_published', '-created_at'], name='services_wo_worker__e237d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='workerreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range'),
        ),
    ]
