# Generated by Django 6.0.4 on 2026-07-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_worker_latitude_worker_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='verification_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='verification_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='verification_tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Auto-verified after MK2000 payment'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['verification_paid'], name='services_wo_verific_2e2ac2_idx'),
        ),
    ]
