# Generated by Django 6.0.4 on 2026-07-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_worker_verification_paid_worker_verification_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Auto-verified after MK2000 payment via PayChangu'),
        ),
    ]
