# Generated by Django 6.0.4 on 2026-07-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_worker_is_verified'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worker',
            name='min_rate_check',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='rate',
        ),
    ]
