# Generated by Django 6.0.4 on 2026-07-13 05:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_conversation_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workerreview',
            name='services_wo_worker__e237d8_idx',
        ),
        migrations.RemoveConstraint(
            model_name='workerreview',
            name='review_rating_range',
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='services_co_partici_acd66e_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='services_co_updated_373372_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='services_me_convers_42640a_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='services_me_recipie_a308a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='worker',
            name='services_wo_verific_2e2ac2_idx',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='trust_score',
            field=models.IntegerField(default=50, help_text='0-100. Below 30 = show scam warning on profile', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='services.worker'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participant_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_conversations_as_p1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participant_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_conversations_as_p2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Show on public site after you verify'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Tick this manually in admin after checking ID'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['trust_score'], name='services_wo_trust_s_e6193c_idx'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='verification_paid',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='verification_paid_at',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='verification_tx_ref',
        ),
        migrations.DeleteModel(
            name='WorkerReview',
        ),
    ]
